apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "coalitieakkoordentool.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
  name: {{ template "coalitieakkoordentool.fullname" . }}
{{ include "coalitieakkoordentool.namespace" . | indent 2 }}
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
  selector:
    {{- include "coalitieakkoordentool.matchLabels" . | nindent 4 }}
